# ORIGINAL 

# FROM golang:1.23.1
#
# # COPY source destination
# COPY . /bin/myapp
#
# CMD ["/bin/myapp"]

# docker build . -t myapp:latest
# docker run -p 8080:8080 goserver

FROM golang:1.23.1

# 1. Put yourself somewhere sensible
WORKDIR /app

# 2. Copy all sources into the container
COPY . .

# 3. Build the binary in-place
RUN go build -o myapp

# 4. Run it by default
CMD ["./myapp"]
