name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest
    name: publish image
    env:
      IMAGE_NAME: myapp/learn-cicd
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: <registry>
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Get Current Timestamp
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the Docker image
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

